//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasierV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CasierContents : DbContext
    {
        public CasierContents()
            : base("name=CasierContents")
        {
            Configuration.ProxyCreationEnabled = false;
            Configuration.LazyLoadingEnabled = false;
            Configuration.ValidateOnSaveEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategorySet> CategorySet { get; set; }
        public virtual DbSet<CreatorSet> CreatorSet { get; set; }
        public virtual DbSet<InvoiceHeaderDetailsSet> InvoiceHeaderDetailsSet { get; set; }
        public virtual DbSet<InvoiceHeaderSet> InvoiceHeaderSet { get; set; }
        public virtual DbSet<ItemSet> ItemSet { get; set; }
        public virtual DbSet<ReservationSet> ReservationSet { get; set; }
        public virtual DbSet<WorkinghoursSet> WorkinghoursSet { get; set; }
    }
}
