//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasierV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreatorSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreatorSet()
        {
            this.InvoiceHeaderSet = new HashSet<InvoiceHeaderSet>();
            this.WorkinghoursSet = new HashSet<WorkinghoursSet>();
        }
    
        public int CreatorId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string CPR { get; set; }
        public Nullable<decimal> MonthSalary { get; set; }
        public Nullable<decimal> HourSalary { get; set; }
        public string Description { get; set; }
        public string Evaluation { get; set; }
        public string BankInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceHeaderSet> InvoiceHeaderSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkinghoursSet> WorkinghoursSet { get; set; }
    }
}
