//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasierV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeaderSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceHeaderSet()
        {
            this.InvoiceHeaderDetailsSet = new HashSet<InvoiceHeaderDetailsSet>();
        }
    
        public int InvoiceHeaderSetId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> CreatorSetCreatorId { get; set; }
        public Nullable<int> ReservationSetReservationId { get; set; }
    
        public virtual CreatorSet CreatorSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceHeaderDetailsSet> InvoiceHeaderDetailsSet { get; set; }
        public virtual ReservationSet ReservationSet { get; set; }
    }
}
