//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasierV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeaderDetailsSet
    {
        public int InvoiceHeaderDetailsId { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public int InvoiceHeaderSetInvoiceHeaderSetId { get; set; }
    
        public virtual InvoiceHeaderSet InvoiceHeaderSet { get; set; }
        public virtual ItemSet ItemSet { get; set; }
    }
}
