//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasierV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemSet()
        {
            this.InvoiceHeaderDetailsSet = new HashSet<InvoiceHeaderDetailsSet>();
        }
    
        public int ItemSetId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> Discount { get; set; }
        public string Description { get; set; }
        public int CategorySetCategoryId { get; set; }
    
        public virtual CategorySet CategorySet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceHeaderDetailsSet> InvoiceHeaderDetailsSet { get; set; }
    }
}
