//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasierV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationSet()
        {
            this.InvoiceHeaderSet = new HashSet<InvoiceHeaderSet>();
        }
    
        public int ReservationId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Amount { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceHeaderSet> InvoiceHeaderSet { get; set; }
    }
}
