//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasierV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkinghoursSet
    {
        public int WorkingHoursId { get; set; }
        public Nullable<System.DateTime> StartHour { get; set; }
        public Nullable<System.DateTime> EndHour { get; set; }
        public int CreatorSetCreatorId { get; set; }
    
        public virtual CreatorSet CreatorSet { get; set; }
    }
}
